-- AlterEnum
ALTER TYPE "MosqueStaffRole" ADD VALUE IF NOT EXISTS 'MUTAWALLI';
ALTER TYPE "MosqueStaffRole" ADD VALUE IF NOT EXISTS 'CUSTOM';

-- AlterTable MosqueStaff
ALTER TABLE "MosqueStaff" ADD COLUMN IF NOT EXISTS "customRoleTitle" TEXT;
ALTER TABLE "MosqueStaff" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "MosqueStaff" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

-- AlterTable MosqueRoleClaim
ALTER TABLE "MosqueRoleClaim" ADD COLUMN IF NOT EXISTS "customRoleTitle" TEXT;
ALTER TABLE "MosqueRoleClaim" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MosqueRoleClaim" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MosqueRoleClaim" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "MosqueRoleClaim" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
